//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateL2L3
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcc_plan
    {
        public int plan_id { get; set; }
        public Nullable<int> domain_id { get; set; }
        public Nullable<int> quarter_id { get; set; }
        public Nullable<int> ecosystem_id { get; set; }
        public string instance_name { get; set; }
        public string project_type { get; set; }
        public string project_desc { get; set; }
        public Nullable<int> pessimistic_days { get; set; }
        public Nullable<int> most_likely_days { get; set; }
        public Nullable<int> optmistic_days { get; set; }
        public Nullable<int> pert_days { get; set; }
        public Nullable<System.DateTime> app_proj_start_dt { get; set; }
        public Nullable<System.DateTime> trans_planning_dt { get; set; }
        public Nullable<System.DateTime> detail_doc_dt { get; set; }
        public Nullable<System.DateTime> app_install_dt { get; set; }
        public Nullable<System.DateTime> test_release_mgmt_dt { get; set; }
        public Nullable<System.DateTime> sys_golive_dt { get; set; }
        public Nullable<System.DateTime> server_decom_dt { get; set; }
        public string bc_dr_comments { get; set; }
        public string key_communication { get; set; }
        public string project_mgr_name { get; set; }
        public string project_mgr_phone { get; set; }
        public string move_package_biz_rep_name { get; set; }
        public string comments { get; set; }
        public string move_package_id { get; set; }
        public string mtp_ovsd_id { get; set; }
        public string pmo_project_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string status_txt { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> create_ts { get; set; }
        public Nullable<System.DateTime> last_update_ts { get; set; }
        public string last_update_user { get; set; }
        public string delete_p { get; set; }
        public string Proj_Scope { get; set; }
        public Nullable<System.DateTime> Hardware_MBS_Commit { get; set; }
        public string ddr_gdba_action_p { get; set; }
        public string ddr_itio_action_p { get; set; }
        public string ddr_app_action_p { get; set; }
        public Nullable<short> ddr_nbr_reviews { get; set; }
        public Nullable<System.DateTime> ddr_review_dt { get; set; }
        public string ddr_complete_p { get; set; }
        public string ddr_denied_p { get; set; }
        public string S2S_p { get; set; }
        public Nullable<int> package_priority { get; set; }
        public Nullable<int> default_need_by_week_id { get; set; }
        public string funding_pmo_project_id { get; set; }
        public string reporting_pmo_project_id { get; set; }
        public Nullable<System.DateTime> package_priority_ts { get; set; }
        public string package_priority_user { get; set; }
        public string ipmDemandPkgNo { get; set; }
        public string ipmTempCust { get; set; }
        public string ipmComments { get; set; }
        public string Classification { get; set; }
        public string CompanyOwner { get; set; }
    }
}
