//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateL2L3
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcc_plan_application
    {
        public int id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<int> epr_id { get; set; }
        public Nullable<int> instance_id { get; set; }
        public string move_package_id { get; set; }
        public string App_CI_Name { get; set; }
    }
}
