//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateL2L3
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcc_biz
    {
        public int biz_id { get; set; }
        public string biz_desc { get; set; }
        public Nullable<bool> visible { get; set; }
    }
}
