//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateL2L3
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcc_biz_domain
    {
        public int biz_domain_id { get; set; }
        public Nullable<int> biz_id { get; set; }
        public string domain_desc { get; set; }
    }
}
