//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateL2L3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DCC_Migration_Data_CollectionEntities : DbContext
    {
        public DCC_Migration_Data_CollectionEntities()
            : base("name=DCC_Migration_Data_CollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dcc_biz> dcc_biz { get; set; }
        public virtual DbSet<dcc_biz_domain> dcc_biz_domain { get; set; }
        public virtual DbSet<dcc_plan_application> dcc_plan_application { get; set; }
        public virtual DbSet<vwUpdateL2L3> vwUpdateL2L3 { get; set; }
        public virtual DbSet<dcc_plan> dcc_plan { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> CreateL2L3(string newL2, string newL3)
        {
            var newL2Parameter = newL2 != null ?
                new ObjectParameter("NewL2", newL2) :
                new ObjectParameter("NewL2", typeof(string));
    
            var newL3Parameter = newL3 != null ?
                new ObjectParameter("NewL3", newL3) :
                new ObjectParameter("NewL3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CreateL2L3", newL2Parameter, newL3Parameter);
        }
    
        public virtual int UpdateMBSBusinessUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMBSBusinessUnit");
        }
    
        public virtual int DeleteUnusedL2L3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUnusedL2L3");
        }
    }
}
